language: php

services:
    - mongodb

env:
    global:
        - MONGO_DRIVER=mongodb

php:
    - 7.0
    - 7.1
    - 7.2
    - nightly

# run build against nightly but allow them to fail
matrix:
    fast_finish: true
    include:
        - php: 5.6
          env: MONGO_DRIVER=mongo
        - php: 7.0
          env: COVERAGE=run
        - php: 7.0
          env: CS_FIXER=run
    allow_failures:
        - php: 7.2
        - php: nightly

# faster builds on new travis setup not using sudo
sudo: false

# cache vendor dirs
cache:
    directories:
        - vendor
        - $HOME/.composer/cache

install:
    - composer self-update

before_script:
    - if [ -n "$GH_TOKEN" ]; then composer config github-oauth.github.com ${GH_TOKEN}; fi;
    - pecl channel-update pecl.php.net
    - yes '' | pecl -q install -f $MONGO_DRIVER
    - if [[ ${TRAVIS_PHP_VERSION:0:2} == "7." || "$TRAVIS_PHP_VERSION" = "nightly" ]]; then composer config "platform.ext-mongo" "1.6.16" && composer require alcaeus/mongo-php-adapter; fi
    - if [ $COVERAGE = run ]; then PHPUNIT_FLAGS="--coverage-clover build/logs/clover.xml"; fi;

script:
    - ant prepare
    - mkdir -p build/logs
    - php bin/simple-phpunit -v $PHPUNIT_FLAGS
    - if [ "$CS_FIXER" = "run" ]; then php bin/php-cs-fixer fix --verbose --dry-run ; fi;

after_script:
    - |
        if [ $COVERAGE = run ]; then
            php bin/coveralls -v
        fi
