imports:
    - { resource: config.yml }

# In production environment you should know that the parameters for URL generation
# always pass the requirements. Otherwise it would break your link (or even site with
# strict_requirements = true). So we can disable the requirements check completely for
# enhanced performance with strict_requirements = null.
framework:
    router:
        strict_requirements: null
    #validation:
    #    cache: apc

monolog:
    handlers:
        main:
            type: fingers_crossed
            action_level: error
            handler: grouped_main
            excluded_404s:
                - ^/
        grouped_main:
            type: group
            members: [streamed_main, sentry]
        streamed_main:
            type: stream
            path: "%kernel.logs_dir%/%kernel.environment%.log"
            level: debug
        sentry:
            type: raven
            dsn: "%sentry_dsn%"
            level: error
        console:
            type: console

doctrine_mongodb:
    document_managers:
        default:
            metadata_cache_driver:
                type: apc

sentry:
    dsn: "%sentry_dsn%"
