imports:
    - { resource: config_dev.yml }
    - { resource: services_test.yml }

framework:
    test: ~
    session:
        storage_id: session.storage.mock_file
    profiler:
        enabled: false

web_profiler:
    toolbar: false
    intercept_redirects: false

security:
    firewalls:
        secured:
            http_basic:

    providers:
        in_memory:
            memory:
                users:
                    admin: { password: "%adminpass%", roles: [ 'ROLE_ADMIN' ] }

doctrine_mongodb:
    default_database: f43me_test
    document_managers:
        default:
            auto_mapping: true
            metadata_cache_driver:
                type: array
