imports:
    - { resource: services/extractors.yml }
    - { resource: services/improvers.yml }
    - { resource: services/converters.yml }
    - { resource: services/parsers.yml }

services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    AppBundle\Content\:
        resource: '../../src/AppBundle/Content'

    AppBundle\Repository\:
        resource: '../../src/AppBundle/Repository'

    AppBundle\Controller\:
        resource: '../../src/AppBundle/Controller'
        public: true
        tags: ['controller.service_arguments']

    # https://coderwall.com/p/4gamjq
    feed.converter.doctrine.mongodb:
        class: Sensio\Bundle\FrameworkExtraBundle\Request\ParamConverter\DoctrineParamConverter
        arguments:
            - "@doctrine_mongodb"
        tags:
            - { name: request.param_converter }

    # external service
    imgur.client:
        class: Imgur\Client
        calls:
            - [ setOption, [ 'client_id', "%imgur.client_id%" ] ]
            - [ setOption, [ 'client_secret', "%imgur.client_secret%" ] ]

    guzzle.client:
        class: GuzzleHttp\Client
        arguments:
            - "%guzzle.options%"

    graby:
        class: Graby\Graby
        arguments:
            -
                error_message: false
                extractor:
                    config_builder:
                        site_config:
                            - "%kernel.root_dir%/site_config"
        calls:
            - [ setLogger, [ "@logger" ] ]
        tags:
            - { name: monolog.logger, channel: graby }

    graby.log_handler:
        class: Graby\Monolog\Handler\GrabyHandler

    twitter.client:
        class: TwitterOAuth\TwitterOAuth
        arguments:
            -
                consumer_key: "%twitter.consumer_key%"
                consumer_secret: "%twitter.consumer_secret%"
                oauth_token: "%twitter.access_token%"
                oauth_token_secret: "%twitter.access_token_secret%"
                output_format: 'array'

    # content_import:
    #     class: AppBundle\Content\Import
    #     arguments:
    #         - "@simple_pie_proxy"
    #         - "@content_extractor"
    #         - "@event_dispatcher"
    #         - "@doctrine.odm.mongodb.document_manager"
    #         - "@monolog.logger.import"

    # custom formatter for import commande (below)
    monolog.import.formatter:
        class: Symfony\Bridge\Monolog\Formatter\ConsoleFormatter
        arguments:
            - "[%%datetime%%] %%start_tag%%%%message%%%%end_tag%% %%context%% %%extra%%\n"

    # content_extractor:
    #     class: AppBundle\Content\Extractor
    #     arguments:
    #         - "@feed.extractor.chain"
    #         - "@feed.improver.chain"
    #         - "@feed.converter.chain"
    #         - "@feed.parser.chain"

    AppBundle\Xml\SimplePieProxy:
        class: AppBundle\Xml\SimplePieProxy
        arguments:
            - "%kernel.root_dir%/cache/simplepie/"
            - 20
            - false

    AppBundle\Xml\Render:
        class: AppBundle\Xml\Render
        arguments:
            - "%domain%"
            - "@doctrine.odm.mongodb.document_manager"
            - "@router"

    feeditem.ping_hub:
        class: AppBundle\EventListener\FeedItemSubscriber
        arguments:
            - "http://pubsubhubbub.appspot.com"
            - "@router"
            - "@guzzle.client"
        tags:
            - { name: kernel.event_listener, event: app.after_item_cached, method: pingHub }

    # validator
    validator.rss.valid_rss:
        class: AppBundle\Validator\Constraints\ConstraintRssValidator
        arguments:
            - "@guzzle.client"
        tags:
            - { name: validator.constraint_validator, alias: valid_rss }
