services:
    # parser
    AppBundle\Parser\ParserChain:
        class: AppBundle\Parser\ParserChain

    feed.parser.external:
        class: AppBundle\Parser\External
        arguments:
            - "@httplug.client.default.http_methods"
            - "%mercury_url%"
        tags:
            -  { name: feed.parser, alias: external }

    feed.parser.internal:
        class: AppBundle\Parser\Internal
        arguments:
            - "@graby"
        tags:
            -  { name: feed.parser, alias: internal }
